
name: Prettier

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier
      run: npx prettier --write .

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore:prettier"
        branch: ${{ github.head_ref }}
