on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
  workflow_dispatch:
    branches:
      - release

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout release
      uses: actions/checkout@v2

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Go into repo directory
      run: cd /root/lefv_io
